
services:
  frontend-service:
    build:
      context: ./../frontend
      dockerfile: ./../frontend/frontend-service.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  brokser-service:
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker-service.dockerfile
    restart: always
    ports:
      - "3600:3600"
    deploy:
      mode: replicated
      replicas: 1
